version: "3.9"

services:
  backend:
    build: ./backend
    container_name: nasa_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: nasa_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
